"""Write an ARR-only copy of a tall table split into two stacked floats (run after nature_tables.py / arr_macros.py).

The review version keeps tables at body size, so a long table can exceed the page height. This copies
sections/<name>.tex to sections/<name>_arr.tex with the tabular split after row N and the header repeated.
The preprint keeps the original file.  Usage: python3 arr_split.py tab_benchmarks 20
"""
import re, sys
name, n = sys.argv[1], int(sys.argv[2])
s = open(f'sections/{name}.tex').read()
spec = re.search(r'\\begin\{tabular\}\{.*?\}(?=\n)', s).group(0)
head = re.search(r'\\toprule\n(.*?\\\\)\n\\midrule\n', s, re.S)
rows_start = head.end()
rows_end = s.index('\\bottomrule', rows_start)
rows = re.findall(r'.*?\\\\(?: *\\rr(?:in\{[^}]*\})?)?\n', s[rows_start:rows_end], re.S)
assert ''.join(rows) == s[rows_start:rows_end], 'row parse mismatch'
first = ''.join(rows[:n]).rstrip()
first = re.sub(r' *\\rr(in\{[^}]*\})?$', '', first) + '\n'
env = 'table*' if '\\begin{table*}' in s else 'table'
pre = s[:rows_start]
part1 = (pre.replace('\\tcap{', '\\tcapdrop{', 1) + first + '\\bottomrule\n\\end{tabular}}\n'
         '\\tabnote{Continued in the next table, which carries the caption.}\n' + f'\\end{{{env}}}\n\n')
part2 = pre + ''.join(rows[n:]) + s[rows_end:]
out = '% generated by arr_split.py from ' + name + '.tex, do not edit\n' + part1 + part2
open(f'sections/{name}_arr.tex', 'w').write(out)
print('wrote', f'sections/{name}_arr.tex', len(rows), 'rows')
