"""Write an ARR-only copy of a multi-float table file with every float split in two (run after make_master.py).

The review version keeps table text at 9pt with wrapping columns, so each float of tab_master_full
is split into two stacked floats with the header repeated. The preprint keeps the original file.
Usage: python3 arr_split_all.py tab_master_full "lcllll" "Y{4.6cm}cY{1.9cm}Y{1.7cm}Y{4.6cm}c"
"""
import re, sys
name, old_spec, new_spec = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(f'sections/{name}.tex').read()
out = ['% generated by arr_split_all.py from ' + name + '.tex, do not edit\n']
for blk in re.findall(r'\\begin\{table\*\}.*?\\end\{table\*\}\n?', s, re.S):
    blk = blk.replace('\\begin{tabular}{%s}' % old_spec, '\\begin{tabular}{%s}' % new_spec)
    head = re.search(r'\\toprule\n(.*?\\\\)\n\\midrule\n', blk, re.S)
    rs, re_ = head.end(), blk.index('\\bottomrule', head.end())
    rows = re.findall(r'.*?\\\\(?: *\\rr(?:in\{[^}]*\})?)?\n', blk[rs:re_], re.S)
    assert ''.join(rows) == blk[rs:re_], 'row parse mismatch'
    n = (len(rows) + 1) // 2
    first = re.sub(r' *\\rr(in\{[^}]*\})?$', '', ''.join(rows[:n]).rstrip()) + '\n'
    pre = blk[:rs]
    out.append(pre.replace('\\tcap{', '\\tcapdrop{', 1) + first + '\\bottomrule\n\\end{tabular}}\n'
               '\\par\\vspace{2pt}{\\footnotesize\\textit{Continued in the next table.}\\par}\n\\end{table*}\n\n')
    out.append(pre + ''.join(rows[n:]) + blk[re_:] + '\n')
open(f'sections/{name}_arr.tex', 'w').write(''.join(out))
print('wrote', f'sections/{name}_arr.tex')
